######################################################################
# Automatically generated by qmake (3.0) lun. févr. 29 18:04:20 2016
######################################################################

TEMPLATE = app
TARGET = RPiSpotQtClient
INCLUDEPATH += .
QT += core gui network

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets 
greaterThan(QT_MAJOR_VERSION, 4): DEFINES += QT5

# Input
HEADERS += RPiSpotQtClient.h
SOURCES += main.cpp RPiSpotQtClient.cpp
